"""Regenerate the browser-readable catalog for opening index.html via file://."""

import csv
import json
from pathlib import Path


def main():
    portfolio = Path(__file__).resolve().parent.parent
    with (portfolio / "tools-manifest.csv").open(encoding="utf-8-sig", newline="") as source:
        rows = list(csv.reader(source))

    headers = [header.strip() for header in rows[0]]
    catalog = [
        {header: (row[index] if index < len(row) else "").strip()
         for index, header in enumerate(headers)}
        for row in rows[1:] if any(value.strip() for value in row)
    ]
    destination = portfolio / "assets" / "tool-catalog.js"
    destination.write_text(
        "// Generated from tools-manifest.csv by scripts/update-tool-catalog.py.\n"
        "// Regenerate after editing the CSV; do not edit this file directly.\n"
        "window.PORTFOLIO_TOOL_CATALOG = "
        + json.dumps(catalog, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Generated {len(catalog)} tools in {destination}")


if __name__ == "__main__":
    main()
